language: python
python:
  - "3.6.6"
# command to install dependencies
before_install:
  - pip install pytest==3.7.1
install:
  - pip install -r requirements.txt
  - python setup.py install
  - python setup_c.py install
# command to run tests
script:
  - pytest tests
